default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres
development:
  <<: *default
  database: portfolio_onebitcodet_development

test: &test
  <<: *default
  database: portfolio_onebitcodet_test
cucumber:
  <<: *test
